name: electron deploy

on:
  push:
    branches:
      - main
jobs:
  release:
    name: build and release electron app
    # 流水线会跑在哪些操作系统中
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # 流水线将分别触发在 windows系统中
        os: [windows-latest]
    steps:
      - name: check out
        uses: actions/checkout@v3.0.0
        # 安装node
      - name: install node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16'
        # 安装依赖
      - name: install
        run: yarn install
        # 打包,发布
      - name: build and publish
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: yarn build:win
        # 上传包
      - name: upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.os }}
          path: dist
        # 上传到release
      - name: release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'dist/**'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
